name: Scribble Racket Doc

on: [push]
  # push:
  #   paths:
  #     - "build.md"
  #     - ".github/workflows/scribble_build-guide.yml"
  #     - "pkgs/racket-build-guide/**"
  # pull_request:
  #   paths:
  #     - "build.md"
  #     - ".github/workflows/scribble_build-guide.yml"
  #     - "pkgs/racket-build-guide/**"

jobs:
  scribble:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: 'current'
    - name: Scribble Racket Doc
      run: sudo raco pkg install --auto -i -j $(nproc) pkgs/racket-doc
