name: Scribble Racket Doc

on: [push]
  # push:
  #   paths:
  #     - "build.md"
  #     - ".github/workflows/scribble_build-guide.yml"
  #     - "pkgs/racket-build-guide/**"
  # pull_request:
  #   paths:
  #     - "build.md"
  #     - ".github/workflows/scribble_build-guide.yml"
  #     - "pkgs/racket-build-guide/**"

jobs:
  scribble:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: 'current'
    - name: Scribble Racket Doc
      run: |
        racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
        echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
        raco pkg config catalogs >> catalog-config.txt
        sudo raco pkg config --set catalogs `cat catalog-config.txt`
        sudo raco pkg update -i --auto pkgs/racket-doc/
